#include <resolv.h>


int dc_res_hnok(const char *);
int dc_res_ownok(const char *);
int dc_res_mailok(const char *);
int dc_res_dnok(const char *);
int dc_sym_ston(const struct res_sym *, const char *, int *);
const char *dc_sym_ntos(const struct res_sym *, int, int *);
const char *dc_sym_ntop(const struct res_sym *, int, int *);
int dc_b64_ntop(u_char const *, size_t, char *, size_t);
int dc_b64_pton(char const *, u_char *, size_t);
int dc_loc_aton(const char *, u_char *);
const char *dc_loc_ntoa(const u_char *, char *);
int dc_dn_skipname(const u_char *, const u_char *);
void dc_putlong(u_int32_t, u_char *);
void dc_putshort(u_int16_t, u_char *);
const char *dc_p_class(int);
const char *dc_p_time(u_int32_t);
const char *dc_p_type(int);
const char *dc_p_rcode(int);
const u_char *dc_p_cdnname(const u_char *, const u_char *, int, FILE *);
const u_char *dc_p_cdname(const u_char *, const u_char *, FILE *);
const u_char *dc_p_fqnname(const u_char *, const u_char *, int, char *, int);
const u_char *dc_p_fqname(const u_char *, const u_char *, FILE *);
const char *dc_p_option(u_long);
char *dc_p_secstodate(u_long);
int dc_dn_count_labels(const char *);
int dc_dn_comp(const char *, u_char *, int, u_char **, u_char **);
int dc_dn_expand(const u_char *, const u_char *, const u_char *, char *, int);
u_int dc_res_randomid(void);
int dc_res_nameinquery(const char *, int, int, const u_char *, const u_char *);
int dc_res_queriesmatch(const u_char *, const u_char *, const u_char *, const u_char *);
const char *dc_p_section(int, int);
int dc_res_ninit(res_state);
int dc_res_nisourserver(const res_state, const struct sockaddr_in *);
void dc_fp_resstat(const res_state, FILE *);
void dc_res_pquery(const res_state, const u_char *, int, FILE *);
const char *dc_res_hostalias(const res_state, const char *, char *, size_t);
int dc_res_nquery(res_state, const char *, int, int, u_char *, int);
int dc_res_nsearch(res_state, const char *, int, int, u_char *, int);
int dc_res_nquerydomain(res_state, const char *, const char *, int, int, u_char *, int);
int dc_res_nmkquery(res_state, int, const char *, int, int, const u_char *, int, const u_char *, u_char *, int);
int dc_res_nsend(res_state, const u_char *, int, u_char *, int);
int dc_res_findzonecut2(res_state, const char *, ns_class, int, char *, size_t, union res_sockaddr_union *, int);
void dc_res_nclose(res_state);
int dc_res_nopt(res_state, int, u_char *, int, int);
void dc_res_ndestroy(res_state);
u_int16_t dc_res_nametoclass(const char *, int *);
u_int16_t dc_res_nametotype(const char *, int *);
void dc_res_setservers(res_state, const union res_sockaddr_union *, int);
int dc_res_getservers(res_state, union res_sockaddr_union *, int);
